### ISSUE TITLE
en_US.UTF-8 not installed. IOther English dialect localisation issue?

### ISSUE THREAD

**Issue by pow248** [ymzong/jimmy-mail#2]
I have en_AU.UTF-8  set up. Because i'm Australian. App looks for en_US.utf-8 and fails to run?

There should be a way that i can run with en_AU.UTF-8 as it's still english? I wonder if this is a similar problem for all the other en_\* prefixes? I don't know whether this is you trying to call something that's not installed on my system or a problem with locale.py itstelf?

Setting LC_ALL manually to en_AU.UTF-8 didn't work. I'd rather not install another localisation on my system.

This works on a Mac set to Australian English so not sure where the problem is.

```
bbcxc@debian-stretch-phenom-ii:~/repositories/download-software/jimmy-mail$ python main.py
+ python main.py
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from IOControl import *
  File "/home/evan/repositories/download-software/jimmy-mail/IOControl.py", line 16, in <module>
    locale.setlocale(locale.LC_ALL,"en_US.UTF-8")
  File "/usr/lib/python2.7/locale.py", line 583, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
bbcxc@debian-stretch-phenom-ii:~/repositories/download-software/jimmy-mail$
```

Cheers,
BBCXC

**Comment by andrejvidic** [comment]
I had a very similar error, installing something else with pip though.

Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/**init**.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 583, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

Overcame it by running these terminal commands:
export LC_ALL="en_AU.UTF-8"
sudo locale-gen en_AU.UTF-8
sudo update-locale
